context/context.go
js/js.go
material/material.go
menu/menu.go
message/message.go
util/error.go
wechat.go

1.golint 命名规范
2.go vet 发现的一些隐藏bug 😢

1.golint 命名规范  2.解决go vet 发现的一些隐藏bug

---

cache/redis.go
js/js.go

1.暴露GetTicket方法
2.timeout使用second单位

export GetTicket

---

message/message.go

add sessionFrom for mini program custom message

add sessionFrom for mini program custom message

---

oauth/oauth.go

fix oauth.Redirect 缺少request

---

.gitignore
material/media.go
message/message.go
server/server.go
wechat.go

* add `debug` field and `SetDebug` method
* skip `Validate` method when debug mode
* add sth to gitignore
* run gofmt

skip-valid-when-debug-mode(fix #82)

---

cache/redis.go

- redis包地址改成最新的
- 新增SetConn方法，以复用项目中现成的redis.Pool

cache.Redis增加SetConn方法，修改redis包地址

---

cache/redis.go
material/material.go
menu/menu.go
user/user.go
util/error.go

* add DecodeWithCommonError function
* add UpdateRemark method

add: user update-remark api

---

message/message.go

https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1453779503&token=&lang=zh_CN

支持微信第三方平台相关接口

---

context/component_access_token.go
context/component_test.go

官方文档 https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1453779503&token=&lang=zh_CN
https://github.com/silenceper/wechat/pull/99

微信第三方平台的授权流程

---

pay/refund.go
util/http.go

添加退款接口，util http增加CA证书

---

user/user.go

根据[官方文档](https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1421140839)对 user.info 调用结果增加适配属性

add: user.info subscribe info

---

context/access_token.go
context/access_token_test.go
context/context.go

Resolve: https://github.com/silenceper/wechat/issues/123

add: 自定义获取 access token 方法

---

message/message.go

Add member card field in message struct

Add member card field

---

message/customer_message.go

The pr provides a whole solution for sending customer message .
I will give example for beego , gin and http router in another pr. Because the example is depends on module in the pr.

add module to send customer message

---

message/message.go
server/server.go

https://developers.weixin.qq.com/miniprogram/dev/api-backend/open-api/sec-check/security.mediaCheckAsync.html
新增个 内容异步审核 消息

增加内容审核相关 message 字段

---

material/material.go

[根据最新的微信文档做了修改](https://developers.weixin.qq.com/doc/offiaccount/Asset_Management/Adding_Permanent_Assets.html)

修复上传永久视频素材, close #180

---

message/message.go
message/text.go

Revert "fix: 序列化 xml 时添加 cdata 标签"

---

device/authorize.go
device/bind.go
device/definitions.go
device/device.go
device/message.go
device/qrcode.go
message/message.go
wechat.go

望大佬审核一些。有问题我再调整一下。目前的接口都已经测试过了可以使用

增加了关于微信智能硬件的一些方式

---

material/material.go

https://developers.weixin.qq.com/doc/offiaccount/Asset_Management/Getting_Permanent_Assets.html

增加获取永久素材接口

---

message/customer_message.go
message/message.go
message/text.go

序列化 xml 时添加 cdata 标签

---

go.mod
go.sum
pay/notify_result.go

https://pay.weixin.qq.com/wiki/doc/api/jsapi.php?chapter=9_7&index=8
在使用信用卡支付时，银行给了优惠。此时 微信返回的 notify 信息了会包含 coupon 相关字段。目前的 验证签名方式，太过死板。

重写 pay/NotifyResult VerifySign

---

go.mod
go.sum
pay/notify_result.go

增加 MsgTypeMiniProgrampage 消息类型

---

README.md
material/material.go

material add BatchGetMaterial
